version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: sosdoc
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sosdoc
      MYSQL_ROOT_PASSWORD: 
